name: test
on:
  push:
  pull_request:

permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test"
    steps:
      - uses: actions/checkout@v3
      - name: "Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
